// 06-mobile-crossplatform/09-ionic-vue/src/components/TodoInput.vue
<template>
  <ion-card class="todo-input-card">
    <ion-card-content>
      <form @submit.prevent="handleSubmit">
        <ion-item lines="none" class="input-item">
          <ion-input
            v-model="inputText"
            placeholder="What needs to be done?"
            :clear-input="true"
            @ionFocus="handleFocus"
            @ionBlur="handleBlur"
          ></ion-input>
          <ion-button
            slot="end"
            :disabled="!inputText.trim()"
            @click="handleSubmit"
            color="primary"
          >
            <ion-icon slot="icon-only" :icon="addCircleOutline"></ion-icon>
          </ion-button>
        </ion-item>
      </form>
      <p v-if="isFocused" class="input-hint">
        <ion-icon :icon="informationCircleOutline"></ion-icon>
        Press Enter or tap + to add
      </p>
    </ion-card-content>
  </ion-card>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import {
  IonCard,
  IonCardContent,
  IonItem,
  IonInput,
  IonButton,
  IonIcon
} from '@ionic/vue'
import { addCircleOutline, informationCircleOutline } from 'ionicons/icons'

// Emits
const emit = defineEmits<{
  (e: 'add-todo', text: string): void
}>()

// State
const inputText = ref('')
const isFocused = ref(false)

// Methods
const handleSubmit = () => {
  const text = inputText.value.trim()
  if (text) {
    emit('add-todo', text)
    inputText.value = ''
  }
}

const handleFocus = () => {
  isFocused.value = true
}

const handleBlur = () => {
  isFocused.value = false
}
</script>

<style scoped>
.todo-input-card {
  margin: 16px;
  margin-top: 8px;
  margin-bottom: 8px;
}

.input-item {
  --padding-start: 0;
  --padding-end: 0;
  --inner-padding-end: 0;
}

.input-hint {
  margin: 8px 0 0;
  font-size: 12px;
  color: var(--ion-color-medium);
  display: flex;
  align-items: center;
  gap: 4px;
}

.input-hint ion-icon {
  font-size: 16px;
}
</style>

// 06-mobile-crossplatform/08-ionic-react/src/components/TodoInput.tsx
import React, { useState, useRef } from 'react';
import {
  IonCard,
  IonCardContent,
  IonItem,
  IonInput,
  IonButton,
  IonIcon,
  useIonToast,
} from '@ionic/react';
import { addCircle } from 'ionicons/icons';
import { Keyboard } from '@capacitor/keyboard';
import './TodoInput.css';

interface TodoInputProps {
  onAddTodo: (text: string) => void;
}

const TodoInput: React.FC<TodoInputProps> = ({ onAddTodo }) => {
  const [inputValue, setInputValue] = useState('');
  const [present] = useIonToast();
  const inputRef = useRef<HTMLIonInputElement>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const trimmedValue = inputValue.trim();

    if (!trimmedValue) {
      present({
        message: 'Please enter a todo item',
        duration: 2000,
        position: 'bottom',
        color: 'warning',
      });
      return;
    }

    if (trimmedValue.length > 200) {
      present({
        message: 'Todo text is too long (max 200 characters)',
        duration: 2000,
        position: 'bottom',
        color: 'danger',
      });
      return;
    }

    onAddTodo(trimmedValue);
    setInputValue('');

    // 在移動設備上隱藏鍵盤
    try {
      await Keyboard.hide();
    } catch (error) {
      // Keyboard plugin not available in web
    }

    // 重新聚焦輸入框
    setTimeout(() => {
      inputRef.current?.setFocus();
    }, 100);
  };

  return (
    <IonCard className="todo-input-card">
      <IonCardContent>
        <form onSubmit={handleSubmit}>
          <IonItem lines="none" className="input-item">
            <IonInput
              ref={inputRef}
              value={inputValue}
              placeholder="What needs to be done?"
              onIonInput={(e) => setInputValue(e.detail.value || '')}
              clearInput
              autocomplete="off"
              enterkeyhint="done"
              className="todo-input"
            />
            <IonButton
              slot="end"
              type="submit"
              color="primary"
              disabled={!inputValue.trim()}
            >
              <IonIcon slot="start" icon={addCircle} />
              Add
            </IonButton>
          </IonItem>
        </form>
      </IonCardContent>
    </IonCard>
  );
};

export default TodoInput;
