// 05-ui-libraries/01-react-mui/src/components/TodoList.tsx
import React from 'react';
import { List, Paper, Typography } from '@mui/material';
import { TodoItem } from './TodoItem';
import { Todo } from '../types';

interface TodoListProps {
  todos: Todo[];
  filter: 'all' | 'active' | 'completed';
  onToggle: (id: number) => void;
  onDelete: (id: number) => void;
}

export const TodoList: React.FC<TodoListProps> = ({
  todos,
  filter,
  onToggle,
  onDelete,
}) => {
  const filteredTodos = todos.filter((todo) => {
    if (filter === 'active') return !todo.completed;
    if (filter === 'completed') return todo.completed;
    return true;
  });

  if (filteredTodos.length === 0) {
    return (
      <Paper elevation={2} sx={{ p: 4, textAlign: 'center' }}>
        <Typography variant="body1" color="text.secondary">
          {filter === 'active' && 'No active tasks. Great job!'}
          {filter === 'completed' && 'No completed tasks yet.'}
          {filter === 'all' && 'No tasks yet. Add one to get started!'}
        </Typography>
      </Paper>
    );
  }

  return (
    <Paper elevation={2}>
      <List sx={{ p: 0 }}>
        {filteredTodos.map((todo) => (
          <TodoItem
            key={todo.id}
            todo={todo}
            onToggle={onToggle}
            onDelete={onDelete}
          />
        ))}
      </List>
    </Paper>
  );
};

// 05-ui-libraries/05-vue-vuetify/src/components/TodoList.vue
<template>
  <v-card elevation="2">
    <v-card-text v-if="todos.length === 0" class="text-center text-grey py-8">
      <v-icon size="64" color="grey-lighten-1">mdi-checkbox-blank-circle-outline</v-icon>
      <p class="text-h6 mt-4">No todos yet</p>
      <p class="text-body-2">Add a new todo to get started!</p>
    </v-card-text>

    <v-list v-else lines="two">
      <template v-for="(todo, index) in todos" :key="todo.id">
        <TodoItem
          :todo="todo"
          @toggle="emit('toggle', $event)"
          @delete="emit('delete', $event)"
        />
        <v-divider v-if="index < todos.length - 1"></v-divider>
      </template>
    </v-list>
  </v-card>
</template>

<script setup lang="ts">
import type { Todo } from '../types'
import TodoItem from './TodoItem.vue'

defineProps<{
  todos: Todo[]
}>()

const emit = defineEmits<{
  toggle: [id: number]
  delete: [id: number]
}>()
</script>
