// 03-modern-frameworks/04-angular/src/app/components/todo-list/todo-list.component.ts
/**
 * Todo List Component
 *
 * Standalone component that displays the list of todos with filtering.
 * Demonstrates Angular 17+ features:
 * - Standalone component
 * - Signal-based state management
 * - Computed values
 * - Control flow syntax (@if, @for, @empty)
 */

import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TodoService } from '../../services/todo.service';
import { TodoItemComponent } from '../todo-item/todo-item.component';
import { FilterType } from '../../models/todo.model';

@Component({
  selector: 'app-todo-list',
  standalone: true,
  imports: [CommonModule, TodoItemComponent],
  template: `
    <div class="todo-list-container">
      <!-- Filter buttons -->
      <div class="filters">
        <button
          *ngFor="let filter of filters"
          (click)="setFilter(filter.value)"
          [class.active]="todoService.filter() === filter.value"
          class="filter-button"
        >
          {{ filter.label }}
          @if (getFilterCount(filter.value) > 0) {
            <span class="filter-badge">{{ getFilterCount(filter.value) }}</span>
          }
        </button>
      </div>

      <!-- Todo list -->
      <div class="todo-list">
        @if (todoService.filteredTodos().length > 0) {
          @for (todo of todoService.filteredTodos(); track todo.id) {
            <app-todo-item
              [todo]="todo"
              (toggle)="handleToggle(todo.id)"
              (delete)="handleDelete(todo.id)"
              (edit)="handleEdit(todo.id, $event)"
            />
          }
        } @else {
          <div class="empty-state">
            @if (todoService.todos().length === 0) {
              <svg width="64" height="64" viewBox="0 0 64 64" fill="none" class="empty-icon">
                <circle cx="32" cy="32" r="30" stroke="#e5e7eb" stroke-width="4"/>
                <path d="M32 20v24M20 32h24" stroke="#e5e7eb" stroke-width="4" stroke-linecap="round"/>
              </svg>
              <h3>No todos yet</h3>
              <p>Add your first todo to get started!</p>
            } @else {
              <svg width="64" height="64" viewBox="0 0 64 64" fill="none" class="empty-icon">
                <circle cx="32" cy="32" r="30" stroke="#8b5cf6" stroke-width="4"/>
                <path d="M20 32l8 8 16-16" stroke="#8b5cf6" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
              <h3>No {{ todoService.filter() }} todos</h3>
              <p>Try a different filter to see more todos.</p>
            }
          </div>
        }
      </div>

      <!-- Footer with statistics and actions -->
      @if (todoService.todos().length > 0) {
        <div class="todo-footer">
          <div class="stats">
            <span class="stat-item">
              <strong>{{ todoService.stats().active }}</strong> active
            </span>
            <span class="stat-divider">•</span>
            <span class="stat-item">
              <strong>{{ todoService.stats().completed }}</strong> completed
            </span>
            <span class="stat-divider">•</span>
            <span class="stat-item">
              <strong>{{ todoService.stats().total }}</strong> total
            </span>
          </div>

          @if (todoService.hasCompletedTodos()) {
            <button
              (click)="handleClearCompleted()"
              class="clear-button"
            >
              Clear Completed
            </button>
          }
        </div>
      }
    </div>
  `,
  styles: [`
    .todo-list-container {
      width: 100%;
    }

    .filters {
      display: flex;
      gap: 8px;
      margin-bottom: 20px;
      background: white;
      padding: 8px;
      border-radius: 12px;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
    }

    .filter-button {
      flex: 1;
      padding: 10px 16px;
      border: 2px solid transparent;
      border-radius: 8px;
      background: transparent;
      color: #6b7280;
      font-size: 14px;
      font-weight: 600;
      cursor: pointer;
      transition: all 0.3s ease;
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 8px;
    }

    .filter-button:hover {
      background: rgba(139, 92, 246, 0.05);
      color: #8b5cf6;
    }

    .filter-button.active {
      background: linear-gradient(135deg, #8b5cf6 0%, #6d28d9 100%);
      color: white;
      box-shadow: 0 4px 12px rgba(139, 92, 246, 0.3);
    }

    .filter-badge {
      background: rgba(255, 255, 255, 0.3);
      padding: 2px 8px;
      border-radius: 12px;
      font-size: 12px;
      font-weight: 700;
    }

    .filter-button.active .filter-badge {
      background: rgba(255, 255, 255, 0.25);
    }

    .todo-list {
      min-height: 200px;
      max-height: 500px;
      overflow-y: auto;
      padding: 4px;
    }

    .todo-list::-webkit-scrollbar {
      width: 8px;
    }

    .todo-list::-webkit-scrollbar-track {
      background: rgba(139, 92, 246, 0.05);
      border-radius: 4px;
    }

    .todo-list::-webkit-scrollbar-thumb {
      background: rgba(139, 92, 246, 0.3);
      border-radius: 4px;
    }

    .todo-list::-webkit-scrollbar-thumb:hover {
      background: rgba(139, 92, 246, 0.5);
    }

    .empty-state {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 60px 20px;
      text-align: center;
    }

    .empty-icon {
      margin-bottom: 20px;
      opacity: 0.5;
      animation: float 3s ease-in-out infinite;
    }

    @keyframes float {
      0%, 100% { transform: translateY(0); }
      50% { transform: translateY(-10px); }
    }

    .empty-state h3 {
      color: #374151;
      font-size: 20px;
      font-weight: 600;
      margin: 0 0 8px 0;
    }

    .empty-state p {
      color: #9ca3af;
      font-size: 14px;
      margin: 0;
    }

    .todo-footer {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 16px;
      margin-top: 20px;
      background: white;
      border-radius: 12px;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
    }

    .stats {
      display: flex;
      align-items: center;
      gap: 12px;
      font-size: 14px;
      color: #6b7280;
    }

    .stat-item {
      display: flex;
      align-items: center;
      gap: 4px;
    }

    .stat-item strong {
      color: #8b5cf6;
      font-weight: 700;
    }

    .stat-divider {
      color: #d1d5db;
    }

    .clear-button {
      padding: 8px 16px;
      background: transparent;
      color: #ef4444;
      border: 2px solid #ef4444;
      border-radius: 8px;
      font-size: 13px;
      font-weight: 600;
      cursor: pointer;
      transition: all 0.3s ease;
    }

    .clear-button:hover {
      background: #ef4444;
      color: white;
      transform: translateY(-1px);
      box-shadow: 0 4px 12px rgba(239, 68, 68, 0.3);
    }

    .clear-button:active {
      transform: translateY(0);
    }

    @media (max-width: 480px) {
      .filters {
        flex-direction: column;
        gap: 6px;
      }

      .todo-footer {
        flex-direction: column;
        gap: 12px;
      }

      .stats {
        font-size: 13px;
      }

      .clear-button {
        width: 100%;
      }
    }
  `]
})
export class TodoListComponent {
  // Inject the TodoService using the new inject() function (Angular 14+)
  // This is an alternative to constructor injection
  todoService = inject(TodoService);

  filters: { label: string; value: FilterType }[] = [
    { label: 'All', value: 'all' },
    { label: 'Active', value: 'active' },
    { label: 'Completed', value: 'completed' }
  ];

  setFilter(filter: FilterType): void {
    this.todoService.setFilter(filter);
  }

  getFilterCount(filter: FilterType): number {
    const stats = this.todoService.stats();
    switch (filter) {
      case 'all':
        return stats.total;
      case 'active':
        return stats.active;
      case 'completed':
        return stats.completed;
      default:
        return 0;
    }
  }

  handleToggle(id: string): void {
    this.todoService.toggleTodo(id);
  }

  handleDelete(id: string): void {
    this.todoService.deleteTodo(id);
  }

  handleEdit(id: string, newText: string): void {
    this.todoService.editTodo(id, newText);
  }

  handleClearCompleted(): void {
    this.todoService.clearCompleted();
  }
}

// 04-metaframeworks/02-nuxt/components/TodoList.vue
<template>
  <div class="todo-list-container">
    <!-- 过滤器 -->
    <div class="filter-container">
      <button
        v-for="filterOption in filters"
        :key="filterOption.value"
        @click="currentFilter = filterOption.value"
        :class="['filter-button', { active: currentFilter === filterOption.value }]"
      >
        {{ filterOption.label }}
      </button>
    </div>

    <!-- 加载状态 -->
    <div v-if="isLoading" class="loading">
      <div class="spinner"></div>
      <p>加载中...</p>
    </div>

    <!-- 错误状态 -->
    <div v-else-if="error" class="error">
      <p>{{ error }}</p>
      <button @click="fetchTodos" class="retry-button">重试</button>
    </div>

    <!-- Todo 列表 -->
    <div v-else-if="filteredTodos.length > 0" class="todo-list">
      <TodoItem
        v-for="todo in filteredTodos"
        :key="todo.id"
        :todo="todo"
      />
    </div>

    <!-- 空状态 -->
    <div v-else class="empty-state">
      <p>{{ emptyMessage }}</p>
    </div>

    <!-- 统计信息 -->
    <div v-if="todos.length > 0" class="stats">
      <span>总计: {{ todos.length }}</span>
      <span>进行中: {{ activeTodosCount }}</span>
      <span>已完成: {{ completedTodosCount }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
// 定义 Todo 类型
interface Todo {
  id: number
  text: string
  completed: boolean
  createdAt: string
}

type FilterType = 'all' | 'active' | 'completed'

// 响应式状态
const todos = ref<Todo[]>([])
const isLoading = ref(true)
const error = ref<string | null>(null)
const currentFilter = ref<FilterType>('all')

// 过滤器选项
const filters = [
  { value: 'all' as FilterType, label: '全部' },
  { value: 'active' as FilterType, label: '进行中' },
  { value: 'completed' as FilterType, label: '已完成' }
]

// 计算属性
const filteredTodos = computed(() => {
  switch (currentFilter.value) {
    case 'active':
      return todos.value.filter(todo => !todo.completed)
    case 'completed':
      return todos.value.filter(todo => todo.completed)
    default:
      return todos.value
  }
})

const activeTodosCount = computed(() =>
  todos.value.filter(todo => !todo.completed).length
)

const completedTodosCount = computed(() =>
  todos.value.filter(todo => todo.completed).length
)

const emptyMessage = computed(() => {
  if (todos.value.length === 0) {
    return '还没有待办事项，添加一个吧！'
  }
  switch (currentFilter.value) {
    case 'active':
      return '没有进行中的待办事项'
    case 'completed':
      return '还没有完成任何待办事项'
    default:
      return '列表为空'
  }
})

// 获取 todos
const fetchTodos = async () => {
  isLoading.value = true
  error.value = null

  try {
    const data = await $fetch<Todo[]>('/api/todos')
    todos.value = data
  } catch (err) {
    console.error('获取 todos 失败:', err)
    error.value = '加载失败，请重试'
  } finally {
    isLoading.value = false
  }
}

// 监听更新事件
const handleTodosUpdate = () => {
  fetchTodos()
}

// 组件挂载时获取数据
onMounted(() => {
  fetchTodos()

  // 监听自定义事件
  if (process.client) {
    window.addEventListener('todosUpdated', handleTodosUpdate)
  }
})

// 组件卸载时清理
onUnmounted(() => {
  if (process.client) {
    window.removeEventListener('todosUpdated', handleTodosUpdate)
  }
})
</script>

<style scoped>
.todo-list-container {
  animation: fadeInUp 0.6s ease-out 0.3s both;
}

.filter-container {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
  background: white;
  padding: 0.5rem;
  border-radius: 10px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.08);
}

.filter-button {
  flex: 1;
  padding: 0.75rem 1rem;
  border: 2px solid transparent;
  background: transparent;
  color: #6b7280;
  border-radius: 6px;
  font-size: 0.95rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
}

.filter-button:hover {
  background: #f3f4f6;
  color: #374151;
}

.filter-button.active {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border-color: transparent;
}

.loading,
.error,
.empty-state {
  text-align: center;
  padding: 3rem 2rem;
  background: white;
  border-radius: 12px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);
}

.loading p,
.error p,
.empty-state p {
  color: #6b7280;
  font-size: 1.1rem;
  margin: 0;
}

.spinner {
  width: 40px;
  height: 40px;
  margin: 0 auto 1rem;
  border: 4px solid #e5e7eb;
  border-top-color: #667eea;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

.error p {
  color: #dc2626;
  margin-bottom: 1rem;
}

.retry-button {
  padding: 0.75rem 1.5rem;
  background: #667eea;
  color: white;
  border: none;
  border-radius: 6px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
}

.retry-button:hover {
  background: #5568d3;
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(102, 126, 234, 0.4);
}

.todo-list {
  margin-bottom: 1.5rem;
}

.stats {
  display: flex;
  justify-content: space-around;
  padding: 1rem;
  background: white;
  border-radius: 10px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.08);
  font-size: 0.9rem;
  color: #6b7280;
  font-weight: 600;
}

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@media (max-width: 640px) {
  .filter-container {
    padding: 0.375rem;
    gap: 0.375rem;
  }

  .filter-button {
    padding: 0.625rem 0.75rem;
    font-size: 0.875rem;
  }

  .stats {
    flex-direction: column;
    gap: 0.5rem;
    text-align: center;
  }
}
</style>
