// 14-state-management/08-vue-vuex/src/components/TodoItem.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useStore } from '../store'
import { Todo } from '../types'

// Props
const props = defineProps<{
  todo: Todo
}>()

const store = useStore()
const isEditing = ref(false)
const editText = ref('')

const toggleTodo = () => {
  // Dispatch action to toggle todo
  store.dispatch('toggleTodo', props.todo.id)
}

const startEdit = () => {
  isEditing.value = true
  editText.value = props.todo.text
}

const cancelEdit = () => {
  isEditing.value = false
  editText.value = ''
}

const saveEdit = () => {
  if (editText.value.trim()) {
    // Dispatch action to update todo
    store.dispatch('updateTodo', {
      id: props.todo.id,
      text: editText.value
    })
  }
  isEditing.value = false
}

const removeTodo = () => {
  // Dispatch action to remove todo
  store.dispatch('removeTodo', props.todo.id)
}

const handleKeyPress = (e: KeyboardEvent) => {
  if (e.key === 'Enter') {
    saveEdit()
  } else if (e.key === 'Escape') {
    cancelEdit()
  }
}
</script>

<template>
  <div :class="['todo-item', { completed: todo.completed }]">
    <div v-if="!isEditing" class="todo-content">
      <input
        type="checkbox"
        :checked="todo.completed"
        @change="toggleTodo"
        class="todo-checkbox"
      />
      <span class="todo-text" @dblclick="startEdit">
        {{ todo.text }}
      </span>
      <div class="todo-actions">
        <button
          class="edit-button"
          @click="startEdit"
          title="Edit todo"
        >
          ✏️
        </button>
        <button
          class="delete-button"
          @click="removeTodo"
          title="Delete todo"
        >
          🗑️
        </button>
      </div>
    </div>

    <div v-else class="todo-edit">
      <input
        v-model="editText"
        type="text"
        class="edit-input"
        @keyup="handleKeyPress"
        @blur="saveEdit"
        autofocus
      />
      <div class="edit-actions">
        <button class="save-button" @click="saveEdit">Save</button>
        <button class="cancel-button" @click="cancelEdit">Cancel</button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.todo-item {
  background: white;
  border-radius: 8px;
  padding: 1rem;
  margin-bottom: 0.5rem;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  transition: all 0.2s;
}

.todo-item:hover {
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);
}

.todo-item.completed {
  opacity: 0.7;
}

.todo-content {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.todo-checkbox {
  width: 1.25rem;
  height: 1.25rem;
  cursor: pointer;
  accent-color: #667eea;
}

.todo-text {
  flex: 1;
  font-size: 1rem;
  color: #2d3748;
  cursor: pointer;
  user-select: none;
}

.todo-item.completed .todo-text {
  text-decoration: line-through;
  color: #a0aec0;
}

.todo-actions {
  display: flex;
  gap: 0.5rem;
  opacity: 0;
  transition: opacity 0.2s;
}

.todo-item:hover .todo-actions {
  opacity: 1;
}

.edit-button,
.delete-button {
  padding: 0.25rem 0.5rem;
  font-size: 1rem;
  background: transparent;
  border: none;
  cursor: pointer;
  border-radius: 4px;
  transition: all 0.2s;
}

.edit-button:hover {
  background: #edf2f7;
}

.delete-button:hover {
  background: #fed7d7;
}

.todo-edit {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.edit-input {
  padding: 0.5rem;
  font-size: 1rem;
  border: 2px solid #667eea;
  border-radius: 4px;
  outline: none;
}

.edit-actions {
  display: flex;
  gap: 0.5rem;
  justify-content: flex-end;
}

.save-button,
.cancel-button {
  padding: 0.375rem 0.75rem;
  font-size: 0.875rem;
  font-weight: 500;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  transition: all 0.2s;
}

.save-button {
  color: white;
  background: #667eea;
}

.save-button:hover {
  background: #5568d3;
}

.cancel-button {
  color: #4a5568;
  background: #e2e8f0;
}

.cancel-button:hover {
  background: #cbd5e0;
}
</style>

// 14-state-management/09-angular-ngrx/src/app/components/todo-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Todo } from '../models/todo.model';

@Component({
  selector: 'app-todo-item',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="todo-item" [class.completed]="todo.completed">
      <input
        type="checkbox"
        [checked]="todo.completed"
        (change)="onToggle()"
        class="checkbox"
      />

      <div class="todo-content" *ngIf="!isEditing" (dblclick)="startEdit()">
        <span class="todo-text">{{ todo.text }}</span>
      </div>

      <input
        *ngIf="isEditing"
        type="text"
        [(ngModel)]="editText"
        (blur)="saveEdit()"
        (keyup.enter)="saveEdit()"
        (keyup.escape)="cancelEdit()"
        class="edit-input"
        #editInput
      />

      <button (click)="onDelete()" class="delete-btn" title="Delete">
        ✕
      </button>
    </div>
  `,
  styles: [`
    .todo-item {
      display: flex;
      align-items: center;
      padding: 15px 20px;
      background: white;
      border-radius: 8px;
      margin-bottom: 10px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      transition: all 0.3s ease;
    }

    .todo-item:hover {
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);
      transform: translateY(-2px);
    }

    .todo-item.completed {
      opacity: 0.6;
      background: #f8f9fa;
    }

    .checkbox {
      width: 20px;
      height: 20px;
      margin-right: 15px;
      cursor: pointer;
      accent-color: #667eea;
    }

    .todo-content {
      flex: 1;
      cursor: pointer;
    }

    .todo-text {
      font-size: 16px;
      color: #2c3e50;
    }

    .todo-item.completed .todo-text {
      text-decoration: line-through;
      color: #95a5a6;
    }

    .edit-input {
      flex: 1;
      padding: 8px 12px;
      border: 2px solid #667eea;
      border-radius: 4px;
      font-size: 16px;
      margin-right: 10px;
    }

    .delete-btn {
      background: #e74c3c;
      color: white;
      padding: 8px 12px;
      border-radius: 4px;
      font-size: 16px;
      font-weight: bold;
      opacity: 0;
      transition: opacity 0.3s ease;
    }

    .todo-item:hover .delete-btn {
      opacity: 1;
    }

    .delete-btn:hover {
      background: #c0392b;
    }
  `],
})
export class TodoItemComponent {
  @Input() todo!: Todo;
  @Output() toggle = new EventEmitter<string>();
  @Output() update = new EventEmitter<{ id: string; text: string }>();
  @Output() delete = new EventEmitter<string>();

  isEditing = false;
  editText = '';

  onToggle(): void {
    this.toggle.emit(this.todo.id);
  }

  onDelete(): void {
    this.delete.emit(this.todo.id);
  }

  startEdit(): void {
    this.isEditing = true;
    this.editText = this.todo.text;
  }

  saveEdit(): void {
    if (this.editText.trim() && this.editText !== this.todo.text) {
      this.update.emit({ id: this.todo.id, text: this.editText.trim() });
    }
    this.isEditing = false;
  }

  cancelEdit(): void {
    this.isEditing = false;
    this.editText = '';
  }
}
