// 08-desktop/02-electron-vue/src/components/TodoItem.vue
<template>
  <div class="todo-item" :class="{ completed: todo.completed, editing: isEditing }">
    <div class="view">
      <input
        class="toggle"
        type="checkbox"
        :checked="todo.completed"
        @change="$emit('toggle', todo.id)"
      />
      <label @dblclick="startEdit">{{ todo.text }}</label>
      <button class="destroy" @click="$emit('delete', todo.id)" title="Delete">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <line x1="18" y1="6" x2="6" y2="18"></line>
          <line x1="6" y1="6" x2="18" y2="18"></line>
        </svg>
      </button>
    </div>
    <input
      v-if="isEditing"
      ref="editInput"
      v-model="editText"
      class="edit"
      type="text"
      @blur="finishEdit"
      @keyup.enter="finishEdit"
      @keyup.esc="cancelEdit"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, nextTick } from 'vue'
import type { Todo } from '../types'

const props = defineProps<{
  todo: Todo
}>()

const emit = defineEmits<{
  toggle: [id: string]
  delete: [id: string]
  update: [id: string, text: string]
}>()

const isEditing = ref(false)
const editText = ref('')
const editInput = ref<HTMLInputElement | null>(null)

const startEdit = () => {
  isEditing.value = true
  editText.value = props.todo.text
  nextTick(() => {
    editInput.value?.focus()
    editInput.value?.select()
  })
}

const finishEdit = () => {
  if (isEditing.value) {
    const trimmed = editText.value.trim()
    if (trimmed) {
      emit('update', props.todo.id, trimmed)
    } else {
      emit('delete', props.todo.id)
    }
    isEditing.value = false
  }
}

const cancelEdit = () => {
  isEditing.value = false
  editText.value = props.todo.text
}
</script>

<style scoped>
.todo-item {
  position: relative;
  background: white;
  border-radius: 8px;
  margin-bottom: 8px;
  padding: 12px 16px;
  border: 2px solid transparent;
  transition: all 0.3s;
  display: flex;
  align-items: center;
}

.todo-item:hover {
  border-color: #e0e0e0;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
}

.view {
  display: flex;
  align-items: center;
  width: 100%;
  gap: 12px;
}

.toggle {
  width: 22px;
  height: 22px;
  cursor: pointer;
  border-radius: 4px;
  flex-shrink: 0;
}

.todo-item label {
  flex: 1;
  font-size: 16px;
  line-height: 1.5;
  cursor: pointer;
  word-break: break-word;
  user-select: none;
}

.completed label {
  color: #999;
  text-decoration: line-through;
}

.destroy {
  opacity: 0;
  width: 32px;
  height: 32px;
  border: none;
  background: #ff6b6b;
  color: white;
  border-radius: 6px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.3s;
  flex-shrink: 0;
}

.todo-item:hover .destroy {
  opacity: 1;
}

.destroy:hover {
  background: #ff5252;
  transform: scale(1.1);
}

.edit {
  width: 100%;
  padding: 12px;
  font-size: 16px;
  border: 2px solid #42b983;
  border-radius: 6px;
  outline: none;
}

.editing .view {
  display: none;
}
</style>

// 14-state-management/09-angular-ngrx/src/app/components/todo-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Todo } from '../models/todo.model';

@Component({
  selector: 'app-todo-item',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="todo-item" [class.completed]="todo.completed">
      <input
        type="checkbox"
        [checked]="todo.completed"
        (change)="onToggle()"
        class="checkbox"
      />

      <div class="todo-content" *ngIf="!isEditing" (dblclick)="startEdit()">
        <span class="todo-text">{{ todo.text }}</span>
      </div>

      <input
        *ngIf="isEditing"
        type="text"
        [(ngModel)]="editText"
        (blur)="saveEdit()"
        (keyup.enter)="saveEdit()"
        (keyup.escape)="cancelEdit()"
        class="edit-input"
        #editInput
      />

      <button (click)="onDelete()" class="delete-btn" title="Delete">
        ✕
      </button>
    </div>
  `,
  styles: [`
    .todo-item {
      display: flex;
      align-items: center;
      padding: 15px 20px;
      background: white;
      border-radius: 8px;
      margin-bottom: 10px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      transition: all 0.3s ease;
    }

    .todo-item:hover {
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);
      transform: translateY(-2px);
    }

    .todo-item.completed {
      opacity: 0.6;
      background: #f8f9fa;
    }

    .checkbox {
      width: 20px;
      height: 20px;
      margin-right: 15px;
      cursor: pointer;
      accent-color: #667eea;
    }

    .todo-content {
      flex: 1;
      cursor: pointer;
    }

    .todo-text {
      font-size: 16px;
      color: #2c3e50;
    }

    .todo-item.completed .todo-text {
      text-decoration: line-through;
      color: #95a5a6;
    }

    .edit-input {
      flex: 1;
      padding: 8px 12px;
      border: 2px solid #667eea;
      border-radius: 4px;
      font-size: 16px;
      margin-right: 10px;
    }

    .delete-btn {
      background: #e74c3c;
      color: white;
      padding: 8px 12px;
      border-radius: 4px;
      font-size: 16px;
      font-weight: bold;
      opacity: 0;
      transition: opacity 0.3s ease;
    }

    .todo-item:hover .delete-btn {
      opacity: 1;
    }

    .delete-btn:hover {
      background: #c0392b;
    }
  `],
})
export class TodoItemComponent {
  @Input() todo!: Todo;
  @Output() toggle = new EventEmitter<string>();
  @Output() update = new EventEmitter<{ id: string; text: string }>();
  @Output() delete = new EventEmitter<string>();

  isEditing = false;
  editText = '';

  onToggle(): void {
    this.toggle.emit(this.todo.id);
  }

  onDelete(): void {
    this.delete.emit(this.todo.id);
  }

  startEdit(): void {
    this.isEditing = true;
    this.editText = this.todo.text;
  }

  saveEdit(): void {
    if (this.editText.trim() && this.editText !== this.todo.text) {
      this.update.emit({ id: this.todo.id, text: this.editText.trim() });
    }
    this.isEditing = false;
  }

  cancelEdit(): void {
    this.isEditing = false;
    this.editText = '';
  }
}
