// 14-state-management/07-vue-pinia/src/components/TodoItem.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useTodoStore } from '../stores/useTodoStore'
import type { Todo } from '../types'

const props = defineProps<{
  todo: Todo
}>()

const todoStore = useTodoStore()
const isEditing = ref(false)
const editText = ref(props.todo.text)

const startEdit = () => {
  isEditing.value = true
  editText.value = props.todo.text
}

const saveEdit = () => {
  if (editText.value.trim()) {
    todoStore.updateTodo(props.todo.id, editText.value)
    isEditing.value = false
  } else {
    cancelEdit()
  }
}

const cancelEdit = () => {
  isEditing.value = false
  editText.value = props.todo.text
}

const handleKeyup = (e: KeyboardEvent) => {
  if (e.key === 'Enter') {
    saveEdit()
  } else if (e.key === 'Escape') {
    cancelEdit()
  }
}
</script>

<template>
  <li class="todo-item" :class="{ completed: todo.completed, editing: isEditing }">
    <div v-if="!isEditing" class="todo-content">
      <input
        type="checkbox"
        :checked="todo.completed"
        @change="todoStore.toggleTodo(todo.id)"
        class="todo-checkbox"
      />
      <span class="todo-text" @dblclick="startEdit">
        {{ todo.text }}
      </span>
      <div class="todo-actions">
        <button @click="startEdit" class="edit-btn" title="編輯">
          ✏️
        </button>
        <button @click="todoStore.removeTodo(todo.id)" class="delete-btn" title="刪除">
          🗑️
        </button>
      </div>
    </div>

    <div v-else class="edit-content">
      <input
        v-model="editText"
        type="text"
        class="edit-input"
        @blur="saveEdit"
        @keyup="handleKeyup"
        ref="editInput"
      />
      <div class="edit-actions">
        <button @click="saveEdit" class="save-btn">✓</button>
        <button @click="cancelEdit" class="cancel-btn">✕</button>
      </div>
    </div>
  </li>
</template>

<style scoped>
.todo-item {
  display: flex;
  align-items: center;
  padding: 1rem;
  background: white;
  border: 2px solid #e2e8f0;
  border-radius: 0.5rem;
  margin-bottom: 0.5rem;
  transition: all 0.2s;
}

.todo-item:hover {
  border-color: #cbd5e0;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
}

.todo-item.completed {
  opacity: 0.6;
  background: #f7fafc;
}

.todo-content {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  width: 100%;
}

.todo-checkbox {
  width: 1.25rem;
  height: 1.25rem;
  cursor: pointer;
  accent-color: #42b883;
}

.todo-text {
  flex: 1;
  font-size: 1rem;
  cursor: pointer;
  user-select: none;
}

.completed .todo-text {
  text-decoration: line-through;
  color: #a0aec0;
}

.todo-actions {
  display: flex;
  gap: 0.5rem;
}

.edit-btn,
.delete-btn {
  padding: 0.25rem 0.5rem;
  background: none;
  border: none;
  cursor: pointer;
  font-size: 1.2rem;
  transition: transform 0.2s;
}

.edit-btn:hover,
.delete-btn:hover {
  transform: scale(1.2);
}

.edit-content {
  display: flex;
  gap: 0.5rem;
  width: 100%;
}

.edit-input {
  flex: 1;
  padding: 0.5rem;
  font-size: 1rem;
  border: 2px solid #42b883;
  border-radius: 0.25rem;
  outline: none;
}

.edit-actions {
  display: flex;
  gap: 0.25rem;
}

.save-btn,
.cancel-btn {
  padding: 0.5rem 0.75rem;
  font-size: 1rem;
  border: none;
  border-radius: 0.25rem;
  cursor: pointer;
  font-weight: bold;
}

.save-btn {
  background: #42b883;
  color: white;
}

.save-btn:hover {
  background: #35a372;
}

.cancel-btn {
  background: #e2e8f0;
  color: #4a5568;
}

.cancel-btn:hover {
  background: #cbd5e0;
}
</style>

// 08-desktop/04-tauri-svelte/src/lib/components/TodoItem.svelte
<script lang="ts">
  import { fade, fly } from 'svelte/transition';
  import { todoActions } from '../stores/todoStore';
  import type { Todo } from '../types/Todo';

  export let todo: Todo;

  let isEditing = false;
  let editText = todo.text;

  function handleToggle() {
    todoActions.toggleTodo(todo.id);
  }

  function handleDelete() {
    todoActions.deleteTodo(todo.id);
  }

  function startEdit() {
    isEditing = true;
    editText = todo.text;
  }

  function saveEdit() {
    if (editText.trim()) {
      todoActions.updateTodo(todo.id, editText.trim());
    }
    isEditing = false;
  }

  function cancelEdit() {
    isEditing = false;
    editText = todo.text;
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter') {
      saveEdit();
    } else if (e.key === 'Escape') {
      cancelEdit();
    }
  }
</script>

<div
  class="todo-item"
  in:fly={{ y: 20, duration: 300 }}
  out:fade={{ duration: 200 }}
>
  <div class="flex items-center gap-3 flex-1">
    <input
      type="checkbox"
      checked={todo.completed}
      on:change={handleToggle}
      class="w-5 h-5 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
    />

    {#if isEditing}
      <input
        type="text"
        bind:value={editText}
        on:keydown={handleKeydown}
        on:blur={saveEdit}
        class="flex-1 px-2 py-1 border border-blue-500 rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
        autofocus
      />
    {:else}
      <span
        class="flex-1 cursor-pointer select-none"
        class:line-through={todo.completed}
        class:text-gray-500={todo.completed}
        on:dblclick={startEdit}
      >
        {todo.text}
      </span>
    {/if}
  </div>

  <div class="flex gap-2">
    {#if !isEditing}
      <button
        on:click={startEdit}
        class="px-3 py-1 text-sm text-blue-600 hover:bg-blue-50 rounded transition-colors"
        title="Edit (double-click)"
      >
        Edit
      </button>
      <button
        on:click={handleDelete}
        class="px-3 py-1 text-sm text-red-600 hover:bg-red-50 rounded transition-colors"
        title="Delete"
      >
        Delete
      </button>
    {/if}
  </div>
</div>

<style>
  .todo-item {
    @apply flex items-center justify-between p-4 bg-white dark:bg-gray-800 rounded-lg shadow-sm hover:shadow-md transition-shadow;
  }
</style>
