// 03-modern-frameworks/01-react/src/components/TodoList.jsx
import TodoItem from './TodoItem'
import './TodoList.css'

function TodoList({ todos, onToggle, onDelete }) {
  if (todos.length === 0) {
    return (
      <ul className="todo-list">
        <li className="empty-state">還沒有任務，添加一個吧！</li>
      </ul>
    )
  }

  return (
    <ul className="todo-list">
      {todos.map(todo => (
        <TodoItem
          key={todo.id}
          todo={todo}
          onToggle={onToggle}
          onDelete={onDelete}
        />
      ))}
    </ul>
  )
}

export default TodoList

// 03-modern-frameworks/10-qwik/src/components/todo-list.tsx
import { component$, type QRL } from '@builder.io/qwik';
import type { Todo } from '../routes';
import { TodoItem } from './todo-item';

interface TodoListProps {
  todos: Todo[];
  onToggle$: QRL<(id: number) => void>;
  onDelete$: QRL<(id: number) => void>;
  onEdit$: QRL<(id: number, text: string) => void>;
}

export const TodoList = component$<TodoListProps>(
  ({ todos, onToggle$, onDelete$, onEdit$ }) => {
    return (
      <div class="divide-y divide-gray-200">
        {todos.map((todo) => (
          <TodoItem
            key={todo.id}
            todo={todo}
            onToggle$={onToggle$}
            onDelete$={onDelete$}
            onEdit$={onEdit$}
          />
        ))}
      </div>
    );
  }
);
