// 03-modern-frameworks/10-qwik/src/components/todo-input.tsx
import { component$, type QRL, type Signal } from '@builder.io/qwik';

interface TodoInputProps {
  value: Signal<string>;
  onAdd$: QRL<() => void>;
  onToggleAll$: QRL<() => void>;
  hasItems: boolean;
  allCompleted: boolean;
}

export const TodoInput = component$<TodoInputProps>(
  ({ value, onAdd$, onToggleAll$, hasItems, allCompleted }) => {
    return (
      <div class="flex gap-3">
        {/* Toggle All Button */}
        {hasItems && (
          <button
            class={`flex-shrink-0 w-12 h-12 rounded-xl flex items-center justify-center transition-all ${
              allCompleted
                ? 'bg-white text-purple-600'
                : 'bg-purple-500 text-white hover:bg-purple-400'
            }`}
            onClick$={onToggleAll$}
            title="Toggle all todos"
            aria-label="Toggle all todos"
          >
            <svg
              class="w-6 h-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M5 13l4 4L19 7"
              />
            </svg>
          </button>
        )}

        {/* Input Field */}
        <div class="flex-1 relative">
          <input
            type="text"
            class="w-full px-6 py-3 rounded-xl text-gray-800 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-white shadow-lg"
            placeholder="What needs to be done?"
            value={value.value}
            onInput$={(e) => {
              value.value = (e.target as HTMLInputElement).value;
            }}
            onKeyDown$={(e) => {
              if (e.key === 'Enter') {
                onAdd$();
              }
            }}
          />
        </div>

        {/* Add Button */}
        <button
          class="flex-shrink-0 px-6 py-3 bg-white text-purple-600 font-semibold rounded-xl hover:bg-purple-50 transition-all shadow-lg"
          onClick$={onAdd$}
        >
          Add
        </button>
      </div>
    );
  }
);

// 08-desktop/02-electron-vue/src/components/TodoInput.vue
<template>
  <div class="todo-input">
    <input
      ref="inputRef"
      v-model="inputValue"
      type="text"
      class="new-todo"
      placeholder="What needs to be done?"
      @keyup.enter="handleSubmit"
      autofocus
    />
    <button
      v-if="inputValue"
      class="add-btn"
      @click="handleSubmit"
      title="Add todo (Enter)"
    >
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <line x1="12" y1="5" x2="12" y2="19"></line>
        <line x1="5" y1="12" x2="19" y2="12"></line>
      </svg>
    </button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const emit = defineEmits<{
  add: [text: string]
}>()

const inputValue = ref('')
const inputRef = ref<HTMLInputElement | null>(null)

const handleSubmit = () => {
  if (inputValue.value.trim()) {
    emit('add', inputValue.value)
    inputValue.value = ''
  }
}

const focus = () => {
  inputRef.value?.focus()
}

defineExpose({ focus })
</script>

<style scoped>
.todo-input {
  position: relative;
  display: flex;
  align-items: center;
  margin-bottom: 20px;
}

.new-todo {
  flex: 1;
  padding: 16px 50px 16px 16px;
  font-size: 18px;
  border: 2px solid #e0e0e0;
  border-radius: 8px;
  outline: none;
  transition: border-color 0.3s;
  background: white;
}

.new-todo:focus {
  border-color: #42b983;
}

.new-todo::placeholder {
  color: #aaa;
  font-style: italic;
}

.add-btn {
  position: absolute;
  right: 8px;
  width: 36px;
  height: 36px;
  border: none;
  border-radius: 6px;
  background: #42b983;
  color: white;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background 0.3s;
}

.add-btn:hover {
  background: #359268;
}

.add-btn svg {
  width: 20px;
  height: 20px;
}
</style>
