// 14-state-management/09-angular-ngrx/src/app/components/todo-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Todo } from '../models/todo.model';

@Component({
  selector: 'app-todo-item',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="todo-item" [class.completed]="todo.completed">
      <input
        type="checkbox"
        [checked]="todo.completed"
        (change)="onToggle()"
        class="checkbox"
      />

      <div class="todo-content" *ngIf="!isEditing" (dblclick)="startEdit()">
        <span class="todo-text">{{ todo.text }}</span>
      </div>

      <input
        *ngIf="isEditing"
        type="text"
        [(ngModel)]="editText"
        (blur)="saveEdit()"
        (keyup.enter)="saveEdit()"
        (keyup.escape)="cancelEdit()"
        class="edit-input"
        #editInput
      />

      <button (click)="onDelete()" class="delete-btn" title="Delete">
        ✕
      </button>
    </div>
  `,
  styles: [`
    .todo-item {
      display: flex;
      align-items: center;
      padding: 15px 20px;
      background: white;
      border-radius: 8px;
      margin-bottom: 10px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      transition: all 0.3s ease;
    }

    .todo-item:hover {
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);
      transform: translateY(-2px);
    }

    .todo-item.completed {
      opacity: 0.6;
      background: #f8f9fa;
    }

    .checkbox {
      width: 20px;
      height: 20px;
      margin-right: 15px;
      cursor: pointer;
      accent-color: #667eea;
    }

    .todo-content {
      flex: 1;
      cursor: pointer;
    }

    .todo-text {
      font-size: 16px;
      color: #2c3e50;
    }

    .todo-item.completed .todo-text {
      text-decoration: line-through;
      color: #95a5a6;
    }

    .edit-input {
      flex: 1;
      padding: 8px 12px;
      border: 2px solid #667eea;
      border-radius: 4px;
      font-size: 16px;
      margin-right: 10px;
    }

    .delete-btn {
      background: #e74c3c;
      color: white;
      padding: 8px 12px;
      border-radius: 4px;
      font-size: 16px;
      font-weight: bold;
      opacity: 0;
      transition: opacity 0.3s ease;
    }

    .todo-item:hover .delete-btn {
      opacity: 1;
    }

    .delete-btn:hover {
      background: #c0392b;
    }
  `],
})
export class TodoItemComponent {
  @Input() todo!: Todo;
  @Output() toggle = new EventEmitter<string>();
  @Output() update = new EventEmitter<{ id: string; text: string }>();
  @Output() delete = new EventEmitter<string>();

  isEditing = false;
  editText = '';

  onToggle(): void {
    this.toggle.emit(this.todo.id);
  }

  onDelete(): void {
    this.delete.emit(this.todo.id);
  }

  startEdit(): void {
    this.isEditing = true;
    this.editText = this.todo.text;
  }

  saveEdit(): void {
    if (this.editText.trim() && this.editText !== this.todo.text) {
      this.update.emit({ id: this.todo.id, text: this.editText.trim() });
    }
    this.isEditing = false;
  }

  cancelEdit(): void {
    this.isEditing = false;
    this.editText = '';
  }
}

// 14-state-management/07-vue-pinia/src/components/TodoItem.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useTodoStore } from '../stores/useTodoStore'
import type { Todo } from '../types'

const props = defineProps<{
  todo: Todo
}>()

const todoStore = useTodoStore()
const isEditing = ref(false)
const editText = ref(props.todo.text)

const startEdit = () => {
  isEditing.value = true
  editText.value = props.todo.text
}

const saveEdit = () => {
  if (editText.value.trim()) {
    todoStore.updateTodo(props.todo.id, editText.value)
    isEditing.value = false
  } else {
    cancelEdit()
  }
}

const cancelEdit = () => {
  isEditing.value = false
  editText.value = props.todo.text
}

const handleKeyup = (e: KeyboardEvent) => {
  if (e.key === 'Enter') {
    saveEdit()
  } else if (e.key === 'Escape') {
    cancelEdit()
  }
}
</script>

<template>
  <li class="todo-item" :class="{ completed: todo.completed, editing: isEditing }">
    <div v-if="!isEditing" class="todo-content">
      <input
        type="checkbox"
        :checked="todo.completed"
        @change="todoStore.toggleTodo(todo.id)"
        class="todo-checkbox"
      />
      <span class="todo-text" @dblclick="startEdit">
        {{ todo.text }}
      </span>
      <div class="todo-actions">
        <button @click="startEdit" class="edit-btn" title="編輯">
          ✏️
        </button>
        <button @click="todoStore.removeTodo(todo.id)" class="delete-btn" title="刪除">
          🗑️
        </button>
      </div>
    </div>

    <div v-else class="edit-content">
      <input
        v-model="editText"
        type="text"
        class="edit-input"
        @blur="saveEdit"
        @keyup="handleKeyup"
        ref="editInput"
      />
      <div class="edit-actions">
        <button @click="saveEdit" class="save-btn">✓</button>
        <button @click="cancelEdit" class="cancel-btn">✕</button>
      </div>
    </div>
  </li>
</template>

<style scoped>
.todo-item {
  display: flex;
  align-items: center;
  padding: 1rem;
  background: white;
  border: 2px solid #e2e8f0;
  border-radius: 0.5rem;
  margin-bottom: 0.5rem;
  transition: all 0.2s;
}

.todo-item:hover {
  border-color: #cbd5e0;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
}

.todo-item.completed {
  opacity: 0.6;
  background: #f7fafc;
}

.todo-content {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  width: 100%;
}

.todo-checkbox {
  width: 1.25rem;
  height: 1.25rem;
  cursor: pointer;
  accent-color: #42b883;
}

.todo-text {
  flex: 1;
  font-size: 1rem;
  cursor: pointer;
  user-select: none;
}

.completed .todo-text {
  text-decoration: line-through;
  color: #a0aec0;
}

.todo-actions {
  display: flex;
  gap: 0.5rem;
}

.edit-btn,
.delete-btn {
  padding: 0.25rem 0.5rem;
  background: none;
  border: none;
  cursor: pointer;
  font-size: 1.2rem;
  transition: transform 0.2s;
}

.edit-btn:hover,
.delete-btn:hover {
  transform: scale(1.2);
}

.edit-content {
  display: flex;
  gap: 0.5rem;
  width: 100%;
}

.edit-input {
  flex: 1;
  padding: 0.5rem;
  font-size: 1rem;
  border: 2px solid #42b883;
  border-radius: 0.25rem;
  outline: none;
}

.edit-actions {
  display: flex;
  gap: 0.25rem;
}

.save-btn,
.cancel-btn {
  padding: 0.5rem 0.75rem;
  font-size: 1rem;
  border: none;
  border-radius: 0.25rem;
  cursor: pointer;
  font-weight: bold;
}

.save-btn {
  background: #42b883;
  color: white;
}

.save-btn:hover {
  background: #35a372;
}

.cancel-btn {
  background: #e2e8f0;
  color: #4a5568;
}

.cancel-btn:hover {
  background: #cbd5e0;
}
</style>
