// 03-modern-frameworks/04-angular/src/app/components/todo-input/todo-input.component.ts
/**
 * Todo Input Component
 *
 * Standalone component for adding new todos.
 * Demonstrates Angular 17+ features:
 * - Standalone component (no NgModule needed)
 * - Two-way data binding with [(ngModel)]
 * - Dependency injection
 * - Template-driven forms
 */

import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TodoService } from '../../services/todo.service';

@Component({
  selector: 'app-todo-input',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="input-container">
      <input
        type="text"
        [(ngModel)]="inputValue"
        (keyup.enter)="handleSubmit()"
        [placeholder]="placeholder()"
        class="todo-input"
        [class.error]="showError()"
        maxlength="200"
        #todoInput
      />
      <button
        (click)="handleSubmit()"
        class="add-button"
        [disabled]="!inputValue.trim()"
      >
        <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
          <path
            d="M10 4V16M4 10H16"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
          />
        </svg>
        Add
      </button>
    </div>
    @if (showError()) {
      <div class="error-message">
        {{ errorMessage() }}
      </div>
    }
  `,
  styles: [`
    .input-container {
      display: flex;
      gap: 12px;
      margin-bottom: 8px;
    }

    .todo-input {
      flex: 1;
      padding: 14px 20px;
      border: 2px solid rgba(139, 92, 246, 0.2);
      border-radius: 12px;
      font-size: 15px;
      transition: all 0.3s ease;
      background: white;
      color: #333;
    }

    .todo-input:focus {
      outline: none;
      border-color: #8b5cf6;
      box-shadow: 0 0 0 3px rgba(139, 92, 246, 0.1);
    }

    .todo-input.error {
      border-color: #ef4444;
    }

    .todo-input::placeholder {
      color: #9ca3af;
    }

    .add-button {
      padding: 14px 28px;
      background: linear-gradient(135deg, #8b5cf6 0%, #6d28d9 100%);
      color: white;
      border: none;
      border-radius: 12px;
      font-size: 15px;
      font-weight: 600;
      cursor: pointer;
      transition: all 0.3s ease;
      display: flex;
      align-items: center;
      gap: 8px;
      box-shadow: 0 4px 12px rgba(139, 92, 246, 0.3);
    }

    .add-button:hover:not(:disabled) {
      transform: translateY(-2px);
      box-shadow: 0 6px 16px rgba(139, 92, 246, 0.4);
    }

    .add-button:active:not(:disabled) {
      transform: translateY(0);
    }

    .add-button:disabled {
      opacity: 0.5;
      cursor: not-allowed;
      box-shadow: none;
    }

    .error-message {
      color: #ef4444;
      font-size: 13px;
      margin-top: -4px;
      margin-left: 4px;
      animation: shake 0.3s ease;
    }

    @keyframes shake {
      0%, 100% { transform: translateX(0); }
      25% { transform: translateX(-5px); }
      75% { transform: translateX(5px); }
    }

    @media (max-width: 480px) {
      .input-container {
        flex-direction: column;
      }

      .add-button {
        width: 100%;
        justify-content: center;
      }
    }
  `]
})
export class TodoInputComponent {
  // Component state using signals
  inputValue = '';
  private showErrorSignal = signal(false);
  private errorMessageSignal = signal('');

  // Expose signals as readonly
  readonly showError = this.showErrorSignal.asReadonly();
  readonly errorMessage = this.errorMessageSignal.asReadonly();

  // Computed placeholder that updates based on stats
  readonly placeholder = signal('What needs to be done?');

  constructor(private todoService: TodoService) {}

  /**
   * Handle form submission
   * Validates input and adds todo if valid
   */
  handleSubmit(): void {
    const trimmedValue = this.inputValue.trim();

    // Reset error state
    this.showErrorSignal.set(false);

    // Validate input
    if (!trimmedValue) {
      this.showErrorSignal.set(true);
      this.errorMessageSignal.set('Please enter a todo item');
      return;
    }

    if (trimmedValue.length < 3) {
      this.showErrorSignal.set(true);
      this.errorMessageSignal.set('Todo must be at least 3 characters');
      return;
    }

    // Add todo via service
    this.todoService.addTodo(trimmedValue);

    // Clear input
    this.inputValue = '';

    // Update placeholder with encouragement
    this.updatePlaceholder();
  }

  /**
   * Update placeholder with dynamic messages
   */
  private updatePlaceholder(): void {
    const count = this.todoService.stats().total;
    const messages = [
      'What else needs to be done?',
      'Add another task...',
      'Keep going! Add more...',
      'What\'s next on your list?',
      'One more task to add?'
    ];
    this.placeholder.set(messages[count % messages.length]);
  }
}

// 08-desktop/03-electron-vue/src/components/TodoInput.vue
<template>
  <div class="todo-input-container">
    <input
      ref="inputRef"
      v-model="inputText"
      @keyup.enter="handleAdd"
      type="text"
      class="todo-input"
      placeholder="添加新的待办事项... (按 Enter 添加)"
      maxlength="200"
    />
    <button @click="handleAdd" class="add-button" :disabled="!inputText.trim()">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
      </svg>
    </button>
    <div class="char-count" v-if="inputText.length > 0">
      {{ inputText.length }}/200
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

// Emits
const emit = defineEmits<{
  (e: 'add-todo', text: string): void;
}>();

// 响应式状态
const inputText = ref('');
const inputRef = ref<HTMLInputElement | null>(null);

// 添加待办事项
function handleAdd() {
  const text = inputText.value.trim();
  if (text) {
    emit('add-todo', text);
    inputText.value = '';
    inputRef.value?.focus();
  }
}

// 聚焦输入框（暴露给父组件）
function focus() {
  inputRef.value?.focus();
}

// 暴露方法给父组件
defineExpose({
  focus,
});
</script>

<style scoped>
.todo-input-container {
  position: relative;
  margin-bottom: 1.5rem;
}

.todo-input {
  width: 100%;
  padding: 1rem 3.5rem 1rem 1rem;
  font-size: 1rem;
  border: 2px solid #e0e0e0;
  border-radius: 8px;
  outline: none;
  transition: all 0.3s;
  font-family: inherit;
}

.todo-input:focus {
  border-color: #667eea;
  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
}

.add-button {
  position: absolute;
  right: 0.5rem;
  top: 50%;
  transform: translateY(-50%);
  width: 40px;
  height: 40px;
  border: none;
  border-radius: 6px;
  background: #667eea;
  color: white;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.3s;
}

.add-button:hover:not(:disabled) {
  background: #5568d3;
  transform: translateY(-50%) scale(1.05);
}

.add-button:disabled {
  background: #ccc;
  cursor: not-allowed;
  opacity: 0.5;
}

.add-button svg {
  width: 24px;
  height: 24px;
}

.char-count {
  position: absolute;
  right: 60px;
  top: 50%;
  transform: translateY(-50%);
  font-size: 0.8rem;
  color: #999;
}

@media (max-width: 768px) {
  .todo-input {
    padding: 0.875rem 3.5rem 0.875rem 0.875rem;
    font-size: 0.95rem;
  }
}
</style>
